# Generated by Django 6.0.3 on 2026-04-27 14:28

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(default=api.models.generate_custom_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(default=api.models.generate_custom_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('semester', models.CharField(default='1', max_length=2)),
                ('departments', models.ManyToManyField(related_name='subjects', to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(default=api.models.generate_custom_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('semester', models.CharField(choices=[('1', 'الترم الاول'), ('2', 'الترم الثاني')], default='1', max_length=2)),
                ('academic_year', models.CharField(blank=True, max_length=50, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='student_covers/')),
                ('current_cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_credits', models.IntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(blank=True, related_name='enrolled_students', to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.CharField(default=api.models.generate_custom_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('hall_location', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_schedules', to='api.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.CharField(default=api.models.generate_custom_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('exam_date', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_exams', to='api.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('todo_id', models.CharField(default=api.models.generate_custom_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_todos', to='api.student')),
            ],
        ),
    ]
