# Generated by Django 6.0.3 on 2026-05-25 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='student',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(help_text='The Leader who added this exam.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_exams', to='api.department'),
        ),
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='hall_location',
            field=models.CharField(blank=True, help_text='Exam hall or location.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='target_level',
            field=models.IntegerField(default=1, help_text='Target academic level for this exam (e.g., 1, 2, 3, 4).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_by',
            field=models.ForeignKey(help_text='The Leader who added this schedule entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_schedules', to='api.department'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='target_level',
            field=models.IntegerField(default=1, help_text='Target academic level for this schedule (e.g., 1, 2, 3, 4).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('leader', 'Leader')], default='student', help_text='Determines if the user can manage schedules.', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='virtual_start_year',
            field=models.IntegerField(blank=True, help_text="Calculated base year used to dynamically determine the student's current level.", null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subject'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subject'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=models.CharField(help_text='Lecture, Lab, Section, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(help_text='e.g., CS101', max_length=20, unique=True),
        ),
    ]
