# Generated by Django 6.0.3 on 2026-05-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_exam_student_remove_schedule_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
