# Generated by Django 6.0.3 on 2026-05-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cohortmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CohortMessage',
        ),
    ]
