# Generated by Django 6.0.3 on 2026-06-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cohortmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('midterm', 'Midterm'), ('final', 'Final'), ('quiz', 'Quiz'), ('practical', 'Practical')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
